- active: true
  event: ocr.success
  multiplier: 1.0
  points: 10
  streak_bonus: 2
- active: true
  event: invoice.paid_on_time
  multiplier: 1.1
  points: 15
  streak_bonus: 0
- active: true
  event: vat.filed_on_time
  multiplier: 1.2
  points: 20
  streak_bonus: 5
- active: true
  event: weekly_ocr5
  multiplier: 1.3
  points: 25
  streak_bonus: 5
- active: true
  event: ai.recommendation_accepted
  multiplier: 1.0
  points: 5
  streak_bonus: 0
- active: true
  event: billing.checkout_completed
  multiplier: 1.0
  points: 20
  streak_bonus: 0
