#!/bin/bash

# Converto Email Setup Script
# This script sets up Converto.fi email with proper DNS and cPanel configuration

echo "🎯 Converto.fi Sähköpostin Asennus"
echo "=================================="

# Configuration
DOMAIN="converto.fi"
EMAIL_SERVER="cpanel"
REGISTERED_NS="ns1.hostingpalvelu.fi"

# Function to check DNS status
check_dns_status() {
    echo "🔍 Tarkistetaan DNS-tilanne..."
    
    # Check MX records
    MX_COUNT=$(dig MX $DOMAIN +short | wc -l)
    if [ "$MX_COUNT" -eq "0" ]; then
        echo "❌ MX-tietueita ei löydy $DOMAIN:llä"
        echo "📝 Tämä tarkoittaa että sähköposti ei toimi"
        return 1
    else
        echo "✅ Löydettiin $MX_COUNT MX-tietuetta:"
        dig MX $DOMAIN +short
        return 0
    fi
}

# Function to create email accounts in cPanel
setup_email_accounts() {
    echo "📧 Luodaan sähköpostitilejä..."
    
    # Email accounts to create
    EMAILS=("hello@converto.fi" "info@converto.fi" "sales@converto.fi" "support@converto.fi")
    
    for EMAIL in "${EMAILS[@]}"; do
        echo "   📬 Luodaan $EMAIL..."
        echo "   🔑 Salasana: [Anna turvallinen salasana]"
        echo "   📁 Kiintolevytila: 1000 MB"
        echo "   ✅ Aktivoitu"
    done
}

# Function to configure DNS records
configure_dns() {
    echo "🌐 Konfiguroidaan DNS-tietueet..."
    
    # MX Records (pointing to cPanel server)
    echo "   📋 Lisättävät MX-tietueet:"
    echo "   1. Host: @ (tai jätä tyhjäksi)"
    echo "      Type: MX"
    echo "      Priority: 10"
    echo "      Value: [cPanel-palvelimen MX-tietue]"
    echo ""
    echo "   2. Host: @"
    echo "      Type: MX" 
    echo "      Priority: 20"
    echo "      Value: [backup MX-tietue]"
    
    # SPF Record
    echo "   📋 SPF-tietue:"
    echo "   Host: @"
    echo "   Type: TXT"
    echo "   Value: v=spf1 +a +mx +ip4:[SERVER_IP] ~all"
    
    # DKIM (usually auto-configured by cPanel)
    echo "   📋 DKIM (automaattinen cPanelissa):"
    echo "   Host: [Auto-generated]"
    echo "   Type: TXT"
    echo "   Value: [Auto-generated by cPanel]"
}

# Function to test email configuration
test_email_config() {
    echo "🧪 Testataan sähköpostin konfiguraatio..."
    
    # Test DNS
    echo "1. DNS-testaus:"
    echo "   dig MX $DOMAIN"
    echo "   dig TXT $DOMAIN | grep spf"
    
    # Test email sending (would require actual mail server)
    echo "2. Lähetystestaus:"
    echo "   echo 'Test message' | mail -s 'Converto Test' hello@$DOMAIN"
    
    # Test MX lookup
    echo "3. MX-haku:"
    echo "   nslookup $DOMAIN"
    echo "   host $DOMAIN"
}

# Function to generate cPanel instructions
generate_cpanel_instructions() {
    echo "📋 cPanel-ohjeet:"
    echo "=================="
    echo ""
    echo "1. 🎯 Kirjaudu cPaneliin:"
    echo "   URL: https://hostingpalvelu.fi/cpanel"
    echo "   Käyttäjätunnus: [Käyttäjätunnus]"
    echo "   Salasana: [Salasana]"
    echo ""
    echo "2. 📧 Email Accounts -osio:"
    echo "   - Siirry: Email → Email Accounts"
    echo "   - Luo sähköpostitilit:"
    echo "     * hello@converto.fi"
    echo "     * info@converto.fi"
    echo "     * sales@converto.fi"
    echo "     * support@converto.fi"
    echo ""
    echo "3. 🌐 Email Routing -osio:"
    echo "   - Siirry: Email → Email Routing"
    echo "   - Varmista että sähköposti reititetään cPanel-palvelimelle"
    echo ""
    echo "4. 📋 MX Entry -osio:"
    echo "   - Siirry: Email → MX Entry"
    echo "   - Tarkista että MX-tietueet on konfiguroitu"
    echo "   - Jos ei, lisää MX-tietueet DNS Zone Editorissa"
    echo ""
    echo "5. 🔧 DNS Zone Editor -osio:"
    echo "   - Siirry: Domains → DNS Zone Editor"
    echo "   - Tarkista MX-tietueet"
    echo "   - Varmista SPF-tietue"
    echo ""
    echo "6. 🔐 Email Security -osio:"
    echo "   - Siirry: Email → Email Authentication"
    echo "   - Ota käyttöön DKIM ja SPF"
    echo ""
    echo "7. 📨 Email Forwarders (tarvittaessa):"
    echo "   - Siirry: Email → Email Forwarders"
    echo "   - Lisää edelleenohjaukset tarvittaessa"
}

# Function to create email service integration
create_email_integration() {
    echo "🔗 Luodaan sähköpostipalvelun integraatio..."
    
    # SMTP settings for Converto
    echo "📧 Converto Sähköpostiasetukset:"
    echo "============================"
    echo ""
    echo "IMAP (Sähköpostin vastaanotto):"
    echo "   Server: mail.converto.fi"
    echo "   Port: 993"
    echo "   Security: SSL/TLS"
    echo "   Username: hello@converto.fi"
    echo ""
    echo "SMTP (Sähköpostin lähetys):"
    echo "   Server: mail.converto.fi"
    echo "   Port: 587"
    echo "   Security: STARTTLS"
    echo "   Authentication: Required"
    echo "   Username: hello@converto.fi"
    echo ""
    echo "POP3 (vaihtoehtoinen):"
    echo "   Server: mail.converto.fi"
    echo "   Port: 995"
    echo "   Security: SSL/TLS"
}

# Function to update environment variables
update_env_config() {
    echo "🔧 Päivitetään ympäristömuuttujat..."
    
    # This would update .env with email configuration
    echo "# Converto Email Configuration" >> .env.tmp
    echo "CONVERTO_EMAIL_ENABLED=true" >> .env.tmp
    echo "CONVERTO_EMAIL_DOMAIN=converto.fi" >> .env.tmp
    echo "CONVERTO_EMAIL_SERVER=mail.converto.fi" >> .env.tmp
    echo "CONVERTO_EMAIL_PORT=587" >> .env.tmp
    echo "CONVERTO_EMAIL_SSL=true" >> .env.tmp
    echo "CONVERTO_EMAIL_USERNAME=hello@converto.fi" >> .env.tmp
    echo "CONVERTO_EMAIL_PASSWORD=[SET_EMAIL_PASSWORD]" >> .env.tmp
    echo "CONVERTO_EMAIL_SMTP_ENABLED=true" >> .env.tmp
    echo "" >> .env.tmp
    
    echo "✅ Luotu .env.tmp - päivitä .env-tiedosto käsin"
}

# Main execution
main() {
    echo "🚀 Aloitetaan Converto sähköpostin asennus..."
    echo "Domain: $DOMAIN"
    echo "Name Server: $REGISTERED_NS"
    echo ""
    
    # Check current DNS status
    if ! check_dns_status; then
        echo "⚠️  DNS-tietueita ei ole konfiguroitu"
        echo "📋 Seuraavat toimet vaaditaan:"
        generate_cpanel_instructions
    else
        echo "✅ DNS-tietueet löydetty"
    fi
    
    echo ""
    echo "📋 Seuraavat toimet:"
    echo "=================="
    
    # Generate instructions
    generate_cpanel_instructions
    create_email_integration
    
    echo ""
    echo "🧪 Testaamisen jälkeen:"
    test_email_config
    
    echo ""
    echo "💡 Vinkit:"
    echo "  • Odota 15-30 min DNS-propagation muutosten jälkeen"
    echo "  • Testaa sähköpostin lähetys ja vastaanotto"
    echo "  • Varmista että SPF ja DKIM ovat käytössä"
    echo "  • Käytä turvallisia salasanoja"
    
    echo ""
    echo "✅ Setup-valmis! Noudata cPanel-ohjeita ylhäältä."
}

# Run main function
main