name: AI Anomaly Detection

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install requests anthropic openai
      - name: Run analyzer
        env:
          PROM_URL: ${{ secrets.PROM_URL || 'http://prometheus:9090' }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/ai_anomaly_detection.py

