name: Deploy Legal

on:
  workflow_dispatch:
    inputs:
      domain_override:
        description: "Optional override domain"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Vercel CLI
        run: npm i -g vercel
      - name: Deploy to Vercel (Legal)
        run: |
          domain="${{ github.event.inputs.domain_override }}"
          if [ -z "$domain" ]; then
            domain="${{ secrets.VERCEL_DOMAIN_LEGAL }}"
          fi
          vercel deploy apps/legal --prod --regions fra1 --token $VERCEL_TOKEN --yes
          vercel domains add $domain --project converto-legal --token=$VERCEL_TOKEN || true
          vercel alias --token=$VERCEL_TOKEN apps/legal $domain || true
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

