name: Deploy Billing

on:
  workflow_dispatch:
    inputs:
      domain_override:
        description: "Optional override domain"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Vercel CLI
        run: npm i -g vercel
      - name: Deploy to Vercel (Billing)
        run: |
          domain="${{ github.event.inputs.domain_override }}"
          if [ -z "$domain" ]; then
            domain="${{ secrets.VERCEL_DOMAIN_BILLING }}"
          fi
          vercel deploy apps/billing --prod --regions fra1 --token $VERCEL_TOKEN --yes
          vercel domains add $domain --project converto-billing --token=$VERCEL_TOKEN || true
          vercel alias --token=$VERCEL_TOKEN apps/billing $domain || true
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

