name: E2E • Playwright

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Install Playwright
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Build app
        working-directory: frontend
        env:
          NEXT_PUBLIC_REGISTRATION_OPEN: "true"
          REGISTRATION_DAYS: "6"
          COMING_SOON: "false"
          STRIPE_ACTIVE: "false"
          NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
        run: npm run build

      - name: Start app
        working-directory: frontend
        env:
          PORT: 3000
        run: |
          npm run start & echo $! > ../pidfile
          npx wait-on http://localhost:3000

      - name: Run Playwright tests
        working-directory: frontend
        env:
          E2E_BASE_URL: "http://localhost:3000"
        run: npx playwright test --reporter=line

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          if-no-files-found: ignore

      - name: Stop server
        if: always()
        run: |
          if [ -f pidfile ]; then kill $(cat pidfile) || true; fi
