name: k6 Load Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup k6
        uses: grafana/setup-k6-action@v1
      - name: Run k6 smoke
        run: k6 run infrastructure/tests/k6/k6_smoke.js
        env:
          TARGET_BASE: ${{ secrets.K6_TARGET_BASE || 'http://localhost:8000' }}

