name: Matrix CI (Python/Postgres)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ '3.10', '3.11' ]
        postgres: [ '14', '15' ]
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}-alpine
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: converto_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pytest psycopg2-binary
      - name: Wait for DB
        run: |
          for i in {1..20}; do
            pg_isready -h localhost -p 5432 -U postgres && break || sleep 2;
          done
      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/converto_db
        run: pytest -q


