name: VAT OSS Monthly Report

on:
  schedule:
    - cron: '0 5 1 * *'  # 1st of month 05:00 UTC
  workflow_dispatch:

jobs:
  vat-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r compliance/requirements.txt
      - name: Run VAT report (tenant_demo)
        env:
          TAX_ADMIN_API_KEY: ${{ secrets.TAX_ADMIN_API_KEY }}
        run: |
          python - << 'PY'
          from compliance.vat_oss_automation import VATOSSAutomation, VATReportType
          import datetime
          import os
          period = datetime.datetime.utcnow().strftime('%Y-%m')
          vat = VATOSSAutomation(tax_admin_api_url=os.getenv('TAX_ADMIN_API_URL','https://api.vero.fi/v1'), api_key=os.getenv('TAX_ADMIN_API_KEY',''))
          import asyncio
          async def main():
              await vat.schedule_vat_reporting('tenant_demo', VATReportType.MONTHLY)
              report = await vat.generate_vat_report('tenant_demo', period, VATReportType.MONTHLY)
              if report:
                  xml = await vat.export_report_xml(report)
                  res = await vat.submit_report_to_tax_admin(report, xml)
                  print(res)
              else:
                  print({'status':'no-data'})
          asyncio.run(main())
          PY

